spring:
  application:
    name: chat
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: minimax-m2.5:cloud

---

spring:
  ai:
    mcp:
      client:
        stdio:
          connections:
            filesystem:
              command: npx
              args:
                - "-y"
                - "@modelcontextprotocol/server-filesystem"
                - "./"
            brightdata:
              command: npx
              args:
                - "@brightdata/mcp"
              env:
                API_TOKEN: "294a35c7-57ea-4d5b-b2dc-4e98a4c6cae8"
        sse:
          connections:
            openhab:
              url: http://localhost:8081
  config:
    activate:
      on-profile: mcp